webosbrew/webos-homebrew-channel

- frontend/views/DetailsPanel.js
Currently manifests in repo uses relative URL for IPKs.
> Supports ipk url related to manifest

- services/service.js
Fixes #15 
Filename is now dynamically generated based on current millisecond-accurate timestamp and by default is only writable by the user running a service (seems like there's a unique uid per service). This now also properly cleans up an incoming file after install.
> service: use dynamic temporary filename for ipk download

- services/elevate-service
Somewhere between webOS 3.8 and 4.3 some changes has been introduced, so that our service is not allowed to install applications by default. This should give us full permissions to whole bus.
This fixes #23
> elevate-service: extend luna-service2 bus permissions

- README.md
- tools/install.sh
We could also extend the guide to getting devmode SSH access without installing the SDK.
Theoretically, the install script should work fine without root.
> tools: single-command install script

- services/startup.sh
Only tested on webOS 2.x, hopefully doesn't break anything on newer versions.
Fixes #78
> Fix root login on webOS 2.x

- appinfo.json
- package.json
- services/service.ts
After extra_conf.sh way got patched, this PR will provide a way to execute `startup.sh`. It works pretty reliable on webOS 4 and up, and should be future-proof as it's not a vulnerability, so it is not likely being patched.
> Autostart Fallback for webOS 4+

- services/service.ts
- services/startup.sh
calling Node.js stuff is quite costly in terms of cpu time on webOS 7
> startup: skip elevation if the script was called by the service itself

- services/elevate-service.ts
- services/service.ts
- services/startup.sh
Currently, it is assumed that the app is installed in `/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service`. This PR makes certain paths either relative or able to be overridden:
* `elevate-service` will now look for `run-js-service` in the same directory as itself and confirm its presence.
* `startup.sh` now looks for a `SERVICE_DIR` environment variable, falling back to the old default if it is not present. (This is needed to find `elevate-service` and `dropbear`.)
`service.ts` now runs `startup.sh` with `SERVICE_DIR` set to the contents of `__dirname`.
> Make some paths relative

- services/adapter.ts
- services/run-js-service
- services/service.ts
* Allow Node.js services to be debugged when `/var/luna/preferences/devmode_enabled` isn't a file
* Fix `updateStartupScript` on old webOS (with Node.js <=v0.12.x)
* Only read `start-devmode.sh` once
> Minor stuff

- services/service.ts
The `/getConfiguration` Luna method now returns the root path of Homebrew Channel's installation as `installRoot`. Currently this will be `/media/developer/apps` in the vast majority of cases, but this feature will make it easier to support installation elsewhere in the future.
While it looks like there are no significant changes to `path.resolve()` between Node.js [v0.10.x](https://nodejs.org/docs/latest-v0.10.x/api/path.html#path_path_resolve_from_to), [v0.12.x](https://nodejs.org/docs/latest-v0.12.x/api/path.html#path_path_resolve_from_to), [v8.x](https://nodejs.org/docs/latest-v8.x/api/path.html#path_path_resolve_paths), [v12.x](https://nodejs.org/docs/latest-v12.x/api/path.html#path_path_resolve_paths), and the [current version](https://nodejs.org/api/path.html#pathresolvepaths), I …
> Add installRoot to /getConfiguration method

- tools/install.sh
The BusyBox `timeout` command's arguments changed starting in webOS 7. It's too annoying to work around, so switch to `luna-send-pub`'s builtin timeout mechanism.
Tested on webOS 6.3.2 and 8.1.0.
> Remove timeout from install.sh

- frontend/configutils.js
Although this probably didn't affect functionality, it was somewhat annoying while debugging.
> Fix warning when repositoriesConfig is missing from localStorage

- services/bin/sampatcher.py
- services/service.ts
It appears nobody ever used `sampatcher.py` (at least unmodified), since it has been using the wrong service name ever since it was first committed: `tv.rootmy.hbchannel.service` instead of `org.webosbrew.hbchannel.service`.
I'm not sure `sampatcher.py` (and the associated method in `service.ts`) really belongs in Homebrew Channel, but I'll leave that for another time.
> Fix service name in sampatcher.py

- .github/workflows/build-binaries.yml
- .github/workflows/build.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
I merged the separate build workflows into a single reusable workflow file. I've tested everything except the PR trigger, but that should work the same as pushing to `main`.
I also updated all action and Node.js versions, so we shouldn't have to worry about deprecation warnings for another few years (except the ones in the actions, but I can't do anything about those).
> Refactor workflows

- services/service.ts
The `/elevateService` method for elevation without having to know the path of the `elevate-service` script.
> Add /elevateService method

- services/service.ts
Fixes a bug that causes `/exec` to fail on webOS 1. Includes a few other improvements.
> Fix /exec on webOS 1

- package-lock.json
- package.json
- services/elevate-service.ts
In an effort to reduce the amount of splitting/merging work, this depends on #169 and includes all of the upcoming strict ESLint work on `elevate-service.ts`.
> Handle non-dev mode paths in elevate-service.ts

- services/adapter.ts
- services/service.ts
Use (promisified) `fs.stat()` instead of `fs.exists()`, which is deprecated. This should not introduce any compatibility issues since we're already using `fs.stat()` elsewhere.
> Replace deprecated fs.exists()

- package-lock.json
- package.json
The webOS OSE CLI tools (`@webosose/ares-cli`) are [deprecated](https://github.com/webosose/ares-cli/commit/f5b4112). They have been replaced with [`@webos-tools/cli`](https://github.com/webos-tools/cli), which supports webOS TV as well.
> Switch to new webOS CLI tools

- services/service.ts
While #172 fixed the basic functionality of `/exec` on webOS 1, the Base64 fields of the response (`stdoutBytes` and `stderrBytes`) were not working as intended.
On Node.js v0.10.x, `child_process.exec()` doesn't appear to support passing stdout and stderr as `Buffer` objects to the callback. However, the `binary` encoding (an alias for `latin1`) can be used to get strings containing the raw program output. After creating `Buffer`s from the strings, the data can be handled the same as on newer webOS/Node.js versions.
I verified that responses containing UTF-8 encoded data were handled identically between webOS 1 and 8.
webOS 8.1.0:
```
{"returnValue":true,"stdoutString":"һȅḽḻ𝖔 𝙛гổḿ ꞩƭᑯ𝞼ʋ𝙩\n","stdoutBytes":"0rvIheG4veG4u/CdlpQg8J2Zm9Cz4buV4bi/IOqeqcat4ZGv8J2evMqL8J2ZqQo=","stderrString":"ȟę …
```
> Fix Base64 output from /exec on webOS 1

- .editorconfig
- .prettierrc
- eslint.config.mjs
- frontend/App.js
- frontend/index.js
- frontend/main.js
- services/adapter.ts
- services/bin/sampatcher.py
- services/service.ts
- services/webos-service-remote/execbus.js
- services/webos-service-remote/message.js
- tools/doas/doas.c
* Removed `.prettierrc`. Settings were mostly moved to `.editorconfig`, but one ended up in `eslint.config.mjs`. Prettier still takes them into account.
* Tweaked some ESLint and EditorConfig settings. The JS settings in `.editorconfig` now cover TS files and additional JS extensions.
* Removed a few unnecessary ESLint disable comments. I used `reportUnusedDisableDirectives`, but I mostly left anything that would be relevant if the associated rule were enabled. The ones I removed were along the lines of `no-unused-vars` on a line with no variables.
* Modified a type to eliminate a suppressed TypeScript error in `adapter.ts`.
* Fixed a handful of spelling mistakes.
* Replaced tabs being used for indentation with spaces. The entire repo is now consistently indented with spaces. I also …
> Miscellaneous cleanup

- services/elevate-service.ts
On webOS 3.5 (and probably 3.0), both the old and new Luna directories are used. Therefore, we have to process the new directory even if a service file is only found in the old one.
When I added support for non-dev Luna directories, I made `elevate-service` skip the ones without a service file to prevent creation of duplicate files. However, webOS 3.x needs API and client permission files in `/var/luna-service2`(`-dev`) even though the service files are in `/var/palm/ls2`(`-dev`). So check the legacy dirs first, and if a service file is found, don't skip the corresponding new dir.
I probably didn't catch this earlier because API and client permission files aren't deleted when an app is removed, so I still had copies from a previous installation.
> Fix elevation on webOS 3.x

- services/better-jail.ts
- services/service.ts
This PR has similar effect as #201, but doesn't fetch any external resource.
For 2019 models with k5lp SoC, default jailer config (`native_devmode`) misses `/dev/rtkmem` causing A/V related apps to crash (e.g. Kodi, Moonlight).
When jailer starts with a different type, device nodes in that jailer config will be created, and persisted even after starting with other types or reboot.
So we start the jailer once with `native` type, creating required device nodes, and the issue gets fixed. There seems to be no negative side effect, as mounting points will not change.
> Populate Native Apps' Jailer on Install

- services/better-jail.ts
- services/service.ts
Reverts webosbrew/webos-homebrew-channel#202
Unfortunately, for some models running webOS 8, this hack doesn't fix anything. Without proper jailer config, native apps won't be able to see external storage at all.
Since this is not a universal solution, I'll make an init script instead, and revert this feature.
> Revert "Populate Native Apps' Jailer on Install"
